trigger:
  batch: true
  branches:
    include:
      - main

pr: [main]

resources:
  repositories:
    - repository: templates
      type: github
      name: microsoft/vscode-engineering
      ref: main
      endpoint: Monaco

parameters:
  - name: publishPackage
    displayName: 🚀 Publish
    type: boolean
    default: false

extends:
  template: azure-pipelines/npm-package/pipeline.yml@templates
  parameters:
    npmPackages:
      - name: vsce
        buildSteps:
          - script: yarn install --frozen-lockfile
          - script: yarn compile
        testPlatforms: []

        publishPackage: ${{ parameters.publishPackage }}
